# ===================================================================
# Server - context
# ===================================================================

server:
  servlet:
    context-path: /learn-api
  port: 9999